# Generated by Django 6.0.1 on 2026-01-31 12:04

from decimal import Decimal
from django.db import migrations, models


def corrigir_dados_invalidos(apps, schema_editor):
    """Ajusta transações com valor <= 0 ou tipo inválido antes de aplicar as constraints."""
    Transacao = apps.get_model('core', 'Transacao')
    for t in Transacao.objects.filter(valor__lte=0):
        t.valor = max(Decimal('0.01'), abs(t.valor))
        t.save()
    Transacao.objects.exclude(tipo__in=['E', 'S']).update(tipo='E')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(corrigir_dados_invalidos, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['E', 'S'])), name='tipo_valido'),
        ),
    ]
